export const categories = [
  { id: '1', name: 'Electronics', icon: '💻', slug: 'electronics', count: 128 },
  { id: '2', name: 'Fashion', icon: '👗', slug: 'fashion', count: 89 },
  { id: '3', name: 'Home & Living', icon: '🏠', slug: 'home-living', count: 64 },
  { id: '4', name: 'Beauty', icon: '💄', slug: 'beauty', count: 43 },
  { id: '5', name: 'Sports', icon: '⚽', slug: 'sports', count: 57 },
  { id: '6', name: 'Toys & Baby', icon: '🧸', slug: 'toys-baby', count: 32 },
  { id: '7', name: 'Automotive', icon: '🚗', slug: 'automotive', count: 21 },
  { id: '8', name: 'Books', icon: '📚', slug: 'books', count: 76 },
];

export const products = [
  {
    id: '1',
    name: 'Wireless Headphones Premium Sound',
    slug: 'wireless-headphones-premium',
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.6,
    reviews: 128,
    sold: 256,
    category: 'Electronics',
    categoryId: '1',
    warehouse: 'AudioWorld Warehouse',
    warehouseRating: 4.7,
    description: 'High quality sound with noise cancellation, long battery life and comfortable design. These wireless headphones deliver premium sound quality with deep bass and crystal clear audio. Perfect for music, calls, and gaming.',
    features: ['Active Noise Cancellation', 'Up to 30 hours battery life', 'Bluetooth 5.3', 'Comfortable over-ear design', 'Built-in microphone'],
    colors: ['Black', 'White', 'Navy'],
    inStock: true,
    stock: 45,
  },
  {
    id: '2',
    name: 'Smart Watch Series 8',
    slug: 'smart-watch-series-8',
    price: 89.99,
    originalPrice: 89.99,
    discount: 0,
    image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.5,
    reviews: 198,
    sold: 412,
    category: 'Electronics',
    categoryId: '1',
    warehouse: 'TechHub Warehouse',
    warehouseRating: 4.8,
    description: 'Advanced smartwatch with health monitoring, GPS, and 48-hour battery life.',
    features: ['Heart rate monitor', 'GPS tracking', 'Sleep tracking', 'Water resistant', '48-hour battery'],
    colors: ['Black', 'Silver', 'Gold'],
    inStock: true,
    stock: 23,
  },
  {
    id: '3',
    name: "Men's Casual Shoes",
    slug: 'mens-casual-shoes',
    price: 49.99,
    originalPrice: 49.99,
    discount: 0,
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.3,
    reviews: 76,
    sold: 189,
    category: 'Fashion',
    categoryId: '2',
    warehouse: 'StylePoint Warehouse',
    warehouseRating: 4.5,
    description: 'Comfortable and stylish casual shoes perfect for everyday wear.',
    features: ['Breathable mesh upper', 'Cushioned insole', 'Rubber outsole', 'Available in multiple sizes'],
    colors: ['Black', 'White', 'Brown'],
    inStock: true,
    stock: 67,
  },
  {
    id: '4',
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    price: 29.99,
    originalPrice: 29.99,
    discount: 0,
    image: 'https://images.pexels.com/photos/1279107/pexels-photo-1279107.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/1279107/pexels-photo-1279107.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.4,
    reviews: 84,
    sold: 203,
    category: 'Electronics',
    categoryId: '1',
    warehouse: 'AudioWorld Warehouse',
    warehouseRating: 4.7,
    description: '360-degree sound with 12-hour battery life and waterproof design.',
    features: ['360 degree sound', '12-hour battery', 'IPX7 waterproof', 'Bluetooth 5.0'],
    colors: ['Black', 'Blue', 'Red'],
    inStock: true,
    stock: 34,
  },
  {
    id: '5',
    name: 'Backpack Travel Bag',
    slug: 'backpack-travel-bag',
    price: 39.99,
    originalPrice: 39.99,
    discount: 0,
    image: 'https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.5,
    reviews: 73,
    sold: 156,
    category: 'Fashion',
    categoryId: '2',
    warehouse: 'StylePoint Warehouse',
    warehouseRating: 4.5,
    description: 'Durable travel backpack with multiple compartments and laptop sleeve.',
    features: ['40L capacity', 'Laptop compartment', 'Water-resistant', 'Ergonomic straps'],
    colors: ['Black', 'Navy', 'Gray'],
    inStock: true,
    stock: 28,
  },
  {
    id: '6',
    name: "Women's Handbag",
    slug: 'womens-handbag',
    price: 34.99,
    originalPrice: 34.99,
    discount: 0,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.2,
    reviews: 97,
    sold: 231,
    category: 'Fashion',
    categoryId: '2',
    warehouse: 'LuxStyle Warehouse',
    warehouseRating: 4.6,
    description: 'Elegant leather handbag with multiple pockets and adjustable strap.',
    features: ['Genuine leather', 'Multiple compartments', 'Adjustable strap', 'Gold hardware'],
    colors: ['Brown', 'Black', 'Tan'],
    inStock: true,
    stock: 42,
  },
  {
    id: '7',
    name: 'Sunglasses UV400',
    slug: 'sunglasses-uv400',
    price: 19.99,
    originalPrice: 19.99,
    discount: 0,
    image: 'https://images.pexels.com/photos/1362558/pexels-photo-1362558.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/1362558/pexels-photo-1362558.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.3,
    reviews: 45,
    sold: 118,
    category: 'Fashion',
    categoryId: '2',
    warehouse: 'LuxStyle Warehouse',
    warehouseRating: 4.6,
    description: 'Polarized sunglasses with UV400 protection and lightweight frame.',
    features: ['UV400 protection', 'Polarized lenses', 'Lightweight frame', 'Scratch resistant'],
    colors: ['Black', 'Brown', 'Gold'],
    inStock: true,
    stock: 89,
  },
  {
    id: '8',
    name: 'Perfume Bottle',
    slug: 'perfume-bottle',
    price: 24.99,
    originalPrice: 24.99,
    discount: 0,
    image: 'https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.6,
    reviews: 93,
    sold: 167,
    category: 'Beauty',
    categoryId: '4',
    warehouse: 'BeautyWorld Warehouse',
    warehouseRating: 4.4,
    description: 'Long-lasting floral fragrance with elegant bottle design.',
    features: ['50ml bottle', 'Long-lasting formula', 'Elegant packaging', 'Floral notes'],
    colors: [],
    inStock: true,
    stock: 52,
  },
  {
    id: '9',
    name: 'Bluetooth Earbuds',
    slug: 'bluetooth-earbuds',
    price: 24.99,
    originalPrice: 34.99,
    discount: 28,
    image: 'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.4,
    reviews: 87,
    sold: 298,
    category: 'Electronics',
    categoryId: '1',
    warehouse: 'AudioWorld Warehouse',
    warehouseRating: 4.7,
    description: 'True wireless earbuds with active noise cancellation and 24-hour battery case.',
    features: ['ANC', '24h battery with case', 'IPX5 waterproof', 'Touch controls'],
    colors: ['Black', 'White'],
    inStock: true,
    stock: 78,
  },
  {
    id: '10',
    name: 'Gaming Mouse',
    slug: 'gaming-mouse',
    price: 27.99,
    originalPrice: 27.99,
    discount: 0,
    image: 'https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.6,
    reviews: 66,
    sold: 145,
    category: 'Electronics',
    categoryId: '1',
    warehouse: 'TechHub Warehouse',
    warehouseRating: 4.8,
    description: 'High precision gaming mouse with RGB lighting and 7 programmable buttons.',
    features: ['16000 DPI sensor', 'RGB lighting', '7 programmable buttons', 'Ergonomic design'],
    colors: ['Black'],
    inStock: true,
    stock: 33,
  },
  {
    id: '11',
    name: 'Fitness Watch',
    slug: 'fitness-watch',
    price: 69.99,
    originalPrice: 89.99,
    discount: 22,
    image: 'https://images.pexels.com/photos/437038/pexels-photo-437038.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/437038/pexels-photo-437038.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.7,
    reviews: 110,
    sold: 334,
    category: 'Electronics',
    categoryId: '1',
    warehouse: 'TechHub Warehouse',
    warehouseRating: 4.8,
    description: 'Advanced fitness tracker with heart rate, GPS, and sleep monitoring.',
    features: ['Heart rate', 'GPS', 'Sleep tracking', 'Blood oxygen', '7-day battery'],
    colors: ['Black', 'Blue', 'Pink'],
    inStock: true,
    stock: 19,
  },
  {
    id: '12',
    name: 'LED Desk Lamp',
    slug: 'led-desk-lamp',
    price: 22.99,
    originalPrice: 22.99,
    discount: 0,
    image: 'https://images.pexels.com/photos/1124982/pexels-photo-1124982.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/1124982/pexels-photo-1124982.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    rating: 4.3,
    reviews: 52,
    sold: 89,
    category: 'Home & Living',
    categoryId: '3',
    warehouse: 'HomeDecor Warehouse',
    warehouseRating: 4.3,
    description: 'Adjustable LED desk lamp with touch dimmer and USB charging port.',
    features: ['Adjustable brightness', 'Color temperature control', 'USB charging port', 'Touch controls'],
    colors: ['White', 'Black'],
    inStock: true,
    stock: 55,
  },
];

export const orders = [
  {
    id: 'MB1256',
    date: 'May 20, 2024',
    items: [
      { productId: '1', name: 'Wireless Headphones', image: products[0].image, price: 59.99, qty: 1 },
      { productId: '10', name: 'Gaming Mouse', image: products[9].image, price: 27.99, qty: 1 },
    ],
    total: 129.99,
    status: 'Delivered',
    shippingAddress: '123 Maple Street, Apt 48, Los Angeles, CA 90001, United States',
    paymentMethod: 'Visa **** 4242',
    shippingMethod: 'Standard Shipping (3-5 business days)',
    subtotal: 129.99,
    discount: 0,
    tax: 0,
    shipping: 0,
    timeline: [
      { status: 'Order Placed', date: 'May 16, 10:24 AM', note: 'Your order has been placed successfully.' },
      { status: 'Processing', date: 'May 18, 11:10 AM', note: 'We are preparing your items.' },
      { status: 'Shipped', date: 'May 19, 09:30 AM', note: 'Your order is on the way.' },
      { status: 'Out for Delivery', date: 'May 20, 08:00 AM', note: 'Your order is out for delivery.' },
      { status: 'Delivered', date: 'May 20, 02:15 PM', note: 'Package delivered successfully.' },
    ],
  },
  {
    id: 'MB1255',
    date: 'May 18, 2024',
    items: [
      { productId: '3', name: "Men's Casual Shoes", image: products[2].image, price: 89.99, qty: 1 },
      { productId: '6', name: "Women's Handbag", image: products[5].image, price: 159.01, qty: 1 },
    ],
    total: 249.00,
    status: 'Shipped',
    shippingAddress: '123 Maple Street, Apt 48, Los Angeles, CA 90001, United States',
    paymentMethod: 'Visa **** 4242',
    shippingMethod: 'Standard Shipping (3-5 business days)',
    subtotal: 249.00,
    discount: 0,
    tax: 0,
    shipping: 0,
    timeline: [
      { status: 'Order Placed', date: 'May 16, 10:24 AM', note: 'Your order has been placed successfully.' },
      { status: 'Processing', date: 'May 18, 11:10 AM', note: 'We are preparing your items.' },
      { status: 'Shipped', date: 'May 19, 09:30 AM', note: 'Your order is on the way.' },
    ],
  },
  {
    id: 'MB1254',
    date: 'May 15, 2024',
    items: [
      { productId: '5', name: 'Backpack Travel Bag', image: products[4].image, price: 89.99, qty: 1 },
    ],
    total: 89.99,
    status: 'Processing',
    shippingAddress: '123 Maple Street, Apt 48, Los Angeles, CA 90001, United States',
    paymentMethod: 'Visa **** 4242',
    shippingMethod: 'Standard Shipping (3-5 business days)',
    subtotal: 89.99,
    discount: 0,
    tax: 0,
    shipping: 0,
    timeline: [
      { status: 'Order Placed', date: 'May 15, 09:00 AM', note: 'Your order has been placed successfully.' },
      { status: 'Processing', date: 'May 16, 10:00 AM', note: 'We are preparing your items.' },
    ],
  },
  {
    id: 'MB1253',
    date: 'May 10, 2024',
    items: [
      { productId: '2', name: 'Smart Watch Series 8', image: products[1].image, price: 89.99, qty: 1 },
      { productId: '4', name: 'Portable Speaker', image: products[3].image, price: 109.01, qty: 1 },
    ],
    total: 199.99,
    status: 'Delivered',
    shippingAddress: '123 Maple Street, Apt 48, Los Angeles, CA 90001, United States',
    paymentMethod: 'Visa **** 4242',
    shippingMethod: 'Standard Shipping',
    subtotal: 199.99,
    discount: 0,
    tax: 0,
    shipping: 0,
    timeline: [],
  },
  {
    id: 'MB1252',
    date: 'May 05, 2024',
    items: [
      { productId: '9', name: 'Bluetooth Earbuds', image: products[8].image, price: 49.99, qty: 1 },
    ],
    total: 49.99,
    status: 'Cancelled',
    shippingAddress: '123 Maple Street, Apt 48, Los Angeles, CA 90001, United States',
    paymentMethod: 'Visa **** 4242',
    shippingMethod: 'Standard Shipping',
    subtotal: 49.99,
    discount: 0,
    tax: 0,
    shipping: 0,
    timeline: [],
  },
  {
    id: 'MB1251',
    date: 'Apr 30, 2024',
    items: [
      { productId: '1', name: 'Wireless Headphones', image: products[0].image, price: 59.99, qty: 1 },
      { productId: '7', name: 'Sunglasses UV400', image: products[6].image, price: 119.01, qty: 1 },
    ],
    total: 179.99,
    status: 'Delivered',
    shippingAddress: '123 Maple Street, Apt 48, Los Angeles, CA 90001, United States',
    paymentMethod: 'Visa **** 4242',
    shippingMethod: 'Express Shipping',
    subtotal: 179.99,
    discount: 0,
    tax: 0,
    shipping: 0,
    timeline: [],
  },
];

export const notifications = [
  {
    id: '1',
    title: 'Order #MB1255 has been shipped',
    message: 'Your order is on the way and will arrive soon.',
    type: 'order',
    time: '2 hours ago',
    read: false,
    icon: 'truck',
  },
  {
    id: '2',
    title: 'Special Offer Just for You!',
    message: 'Get 20% off on your next purchase.',
    type: 'promotion',
    time: '1 day ago',
    read: false,
    icon: 'tag',
  },
  {
    id: '3',
    title: 'Order Delivered',
    message: 'Your order #MB1253 has been delivered successfully.',
    type: 'order',
    time: '3 days ago',
    read: true,
    icon: 'check-circle',
  },
  {
    id: '4',
    title: 'Price Drop Alert',
    message: 'An item in your wishlist is now at a lower price.',
    type: 'system',
    time: '5 days ago',
    read: true,
    icon: 'trending-down',
  },
  {
    id: '5',
    title: 'Profile Update Successful',
    message: 'Your profile information has been updated.',
    type: 'account',
    time: '1 week ago',
    read: true,
    icon: 'user',
  },
];

export const reviews = [
  {
    id: '1',
    productId: '1',
    productName: 'Wireless Headphones',
    productImage: products[0].image,
    productPrice: 59.99,
    rating: 5,
    comment: 'Great sound quality!\n\nThe sound quality is amazing and very comfortable to wear. Battery life is also excellent.',
    date: 'May 18, 2024',
  },
  {
    id: '2',
    productId: '2',
    productName: 'Smart Watch Series 8',
    productImage: products[1].image,
    productPrice: 89.99,
    rating: 4,
    comment: 'Excellent smartwatch\n\nLove the display and the features. Health tracking is very accurate.',
    date: 'May 10, 2024',
  },
  {
    id: '3',
    productId: '3',
    productName: "Men's Casual Shoes",
    productImage: products[2].image,
    productPrice: 49.99,
    rating: 4,
    comment: 'Comfortable and stylish\n\nVery comfortable for daily wear and looks great with jeans.',
    date: 'Apr 28, 2024',
  },
  {
    id: '4',
    productId: '6',
    productName: "Women's Handbag",
    productImage: products[5].image,
    productPrice: 34.99,
    rating: 5,
    comment: 'Perfect size\n\nNice quality and perfect size for daily use. Highly recommended.',
    date: 'Apr 15, 2024',
  },
  {
    id: '5',
    productId: '4',
    productName: 'Portable Speaker',
    productImage: products[3].image,
    productPrice: 29.99,
    rating: 4,
    comment: 'Good for the price\n\nSound is clear and loud for its size. Great for travel.',
    date: 'Apr 05, 2024',
  },
];

export const addresses = [
  {
    id: '1',
    label: 'Home',
    name: 'Sarah Johnson',
    phone: '+1 (555) 123-4567',
    address: '123 Maple Street, Apt 48',
    city: 'Los Angeles, CA 90001',
    country: 'United States',
    isDefault: true,
    type: 'default',
  },
  {
    id: '2',
    label: 'Office',
    name: 'Sarah Johnson',
    phone: '+1 (555) 123-4568',
    address: '500 Business Center Drive, Suite 200',
    city: 'New York, NY 10001',
    country: 'United States',
    isDefault: false,
    type: 'shipping',
  },
  {
    id: '3',
    label: "Parents Home",
    name: 'Sarah Johnson',
    phone: '+1 (555) 123-4569',
    address: '45 Oak Avenue',
    city: 'Austin, TX 73301',
    country: 'United States',
    isDefault: false,
    type: 'shipping',
  },
];
